exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('jobs').del()
    .then(function () {
      // Inserts seed entries
      return knex('jobs').insert([
        { 
          auth_id: 'auth0|66c110e0664fea6c618c6f82',
          job_title: 'Software Engineer', 
          salary: '$100,000', 
          company_name: 'TechCorp', 
          location: 'San Francisco, CA', 
          url: 'https://www.techcorp.com',
          description: 'Develop and maintain web applications.', 
          status: 'discovered',
        },
        { 
          auth_id: 'auth0|66c110e0664fea6c618c6f82',
          job_title: 'UX Designer', 
          salary: '$95,000', 
          company_name: 'Creative Solutions', 
          location: 'Austin, TX', 
          url: 'https://www.creativesolutions.design',
          description: 'Design user-friendly interfaces for web and mobile applications.', 
          status: 'discovered',
        },
        { 
          auth_id: 'auth0|66c110e0664fea6c618c6f82',
          job_title: 'Product Manager', 
          salary: '$120,000', 
          company_name: 'InnovateX', 
          location: 'New York, NY', 
          url: 'https://www.innovatex.ai',
          description: 'Oversee product development and strategy.', 
          status: 'applied',
        },
        { 
          auth_id: 'auth0|66c110e0664fea6c618c6f82',
          job_title: 'Front-End Developer', 
          salary: '$110,000', 
          company_name: 'WebWorks', 
          location: 'Seattle, WA', 
          url: 'https://www.webworks.dev',
          description: 'Build responsive websites and web applications.', 
          status: 'applied',
        },
        { 
          auth_id: 'auth0|66c110e0664fea6c618c6f82',
          job_title: 'Data Analyst', 
          salary: '$90,000', 
          company_name: 'DataInsights', 
          location: 'Chicago, IL', 
          url: 'https://www.datainsights.co',
          description: 'Analyze data and generate reports.', 
          status: 'reached out',
        },
        { 
          auth_id: 'auth0|66c110e0664fea6c618c6f82',
          job_title: 'Marketing Specialist', 
          salary: '$85,000', 
          company_name: 'MarketMasters', 
          location: 'Los Angeles, CA', 
          url: 'https://www.marketmasters.agency',
          description: 'Develop and execute marketing campaigns.', 
          status: 'reached out',
        },
        { 
          auth_id: 'auth0|66c110e0664fea6c618c6f82',
          job_title: 'Backend Developer', 
          salary: '$105,000', 
          company_name: 'CodeCraft', 
          location: 'Denver, CO', 
          url: 'https://www.codecraft.io',
          description: 'Develop and maintain server-side logic and databases.', 
          status: 'interviewing',
        },
        { 
          auth_id: 'auth0|66c110e0664fea6c618c6f82',
          job_title: 'Systems Analyst', 
          salary: '$100,000', 
          company_name: 'SysTech', 
          location: 'Boston, MA', 
          url: 'https://www.systech.com',
          description: 'Analyze and improve IT systems.', 
          status: 'interviewing',
        },
        { 
          auth_id: 'auth0|66c110e0664fea6c618c6f82',
          job_title: 'Project Manager', 
          salary: '$115,000', 
          company_name: 'BuildIt', 
          location: 'Philadelphia, PA', 
          url: 'https://www.buildit.co',
          description: 'Manage and deliver construction projects.', 
          status: 'interviewing',
        },
        { 
          auth_id: 'auth0|66c110e0664fea6c618c6f82',
          job_title: 'DevOps Engineer', 
          salary: '$130,000', 
          company_name: 'CloudServices', 
          location: 'San Jose, CA', 
          url: 'https://www.cloudservices.net',
          description: 'Implement and maintain CI/CD pipelines.', 
          status: 'offer received',
        },
        { 
          auth_id: 'auth0|66c110e0664fea6c618c6f82',
          job_title: 'Sales Engineer', 
          salary: '$110,000', 
          company_name: 'TechSales', 
          location: 'Atlanta, GA', 
          url: 'https://www.techsales.io',
          description: 'Bridge the gap between technical and sales teams.', 
          status: 'offer received',
        },
        { 
          auth_id: 'auth0|66c110e0664fea6c618c6f82',
          job_title: 'Full Stack Developer', 
          salary: '$120,000', 
          company_name: 'InnovateTech', 
          location: 'Portland, OR', 
          url: 'https://www.innovatetech.com',
          description: 'Work on both front-end and back-end development.', 
          status: 'hired',
        },
        { 
          auth_id: 'auth0|66c110e0664fea6c618c6f82',
          job_title: 'Network Engineer', 
          salary: '$95,000', 
          company_name: 'NetSolutions', 
          location: 'Dallas, TX', 
          url: 'https://www.netsolutions.com',
          description: 'Design and manage network infrastructure.', 
          status: 'hired',
        },
        { 
          auth_id: 'auth0|66c110e0664fea6c618c6f82',
          job_title: 'Content Writer', 
          salary: '$70,000', 
          company_name: 'WriteRight', 
          location: 'Miami, FL', 
          url: 'https://www.writeright.co',
          description: 'Create compelling content for various platforms.', 
          status: 'ghosted',
        },
        { 
          auth_id: 'auth0|66c111046b019857b871a9fd',
          job_title: 'Database Administrator', 
          salary: '$110,000', 
          company_name: 'DataGuard', 
          location: 'Houston, TX', 
          url: 'https://www.dataguard.com',
          description: 'Manage and maintain database systems.', 
          status: 'discovered',
        },
        { 
          auth_id: 'auth0|66c111046b019857b871a9fd',
          job_title: 'Security Analyst', 
          salary: '$105,000', 
          company_name: 'SecureNet', 
          location: 'Phoenix, AZ', 
          url: 'https://www.securenet.com',
          description: 'Monitor and protect network infrastructure.', 
          status: 'discovered',
        },
        { 
          auth_id: 'auth0|66c111046b019857b871a9fd',
          job_title: 'Mobile Developer', 
          salary: '$115,000', 
          company_name: 'AppDevCo', 
          location: 'Salt Lake City, UT', 
          url: 'https://www.appdevco.com',
          description: 'Develop mobile applications for Android and iOS.', 
          status: 'applied',
        },
        { 
          auth_id: 'auth0|66c111046b019857b871a9fd',
          job_title: 'IT Manager', 
          salary: '$125,000', 
          company_name: 'IT Solutions', 
          location: 'Charlotte, NC', 
          url: 'https://www.itsolutions.com',
          description: 'Oversee and manage IT operations and staff.', 
          status: 'applied',
        },
        { 
          auth_id: 'auth0|66c111046b019857b871a9fd',
          job_title: 'Cloud Architect', 
          salary: '$135,000', 
          company_name: 'CloudGen', 
          location: 'Orlando, FL', 
          url: 'https://www.cloudgen.com',
          description: 'Design and manage cloud architecture.', 
          status: 'reached out',
        },
        { 
          auth_id: 'auth0|66c111046b019857b871a9fd',
          job_title: 'Technical Support Specialist', 
          salary: '$75,000', 
          company_name: 'HelpDesk', 
          location: 'Columbus, OH', 
          url: 'https://www.helpdesk.com',
          description: 'Provide technical support to clients and customers.', 
          status: 'reached out',
        },
        { 
          auth_id: 'auth0|66c111046b019857b871a9fd',
          job_title: 'Solutions Architect', 
          salary: '$140,000', 
          company_name: 'SolutionWorks', 
          location: 'Indianapolis, IN', 
          url: 'https://www.solutionworks.com',
          description: 'Design and implement IT solutions for clients.', 
          status: 'interviewing',
        },
        { 
          auth_id: 'auth0|66c111046b019857b871a9fd',
          job_title: 'QA Engineer', 
          salary: '$90,000', 
          company_name: 'QualityFirst', 
          location: 'Nashville, TN', 
          url: 'https://www.qualityfirst.com',
          description: 'Test and ensure the quality of software products.', 
          status: 'interviewing',
        },
        { 
          auth_id: 'auth0|66c111046b019857b871a9fd',
          job_title: 'Network Architect', 
          salary: '$125,000', 
          company_name: 'NetArchitects', 
          location: 'San Diego, CA', 
          url: 'https://www.netarchitects.com',
          description: 'Design and build complex network systems.', 
          status: 'offer received',
        },
        { 
          auth_id: 'auth0|66c111046b019857b871a9fd',
          job_title: 'Business Analyst', 
          salary: '$85,000', 
          company_name: 'BizSolutions', 
          location: 'New Orleans, LA', 
          url: 'https://www.bizsolutions.com',
          description: 'Analyze business processes and provide solutions.', 
          status: 'offer received',
        },
        { 
          auth_id: 'auth0|66c111046b019857b871a9fd',
          job_title: 'Scrum Master', 
          salary: '$105,000', 
          company_name: 'AgileWorks', 
          location: 'Detroit, MI', 
          url: 'https://www.agileworks.com',
          description: 'Facilitate Scrum processes in Agile teams.', 
          status: 'hired',
        },
        { 
          auth_id: 'auth0|66c111046b019857b871a9fd',
          job_title: 'Technical Writer', 
          salary: '$80,000', 
          company_name: 'TechDocs', 
          location: 'St. Louis, MO', 
          url: 'https://www.techdocs.com',
          description: 'Create and maintain technical documentation.', 
          status: 'hired',
        },
        { 
          auth_id: 'auth0|66c111046b019857b871a9fd',
          job_title: 'Graphic Designer', 
          salary: '$70,000', 
          company_name: 'DesignStudio', 
          location: 'Las Vegas, NV', 
          url: 'https://www.designstudio.com',
          description: 'Design graphics for digital and print media.', 
          status: 'ghosted',
        }
      ]);
    });
};